### PR TITLE
PR#10 + fix for heroku + applied last commits which were not in #10

### PR DESCRIPTION
**Pull request by danielstaleiny**
Working version of the PR -> https://test-aoe2-build.herokuapp.com/

I managed to re-create the last PR#10 but with fix for heroku app and re-applied turks commit change from 0.15 -> 0.2 on ration. 

I cleaned up files so there is no confusion as well. 

It should work now and all the changes introduced in https://github.com/PeterWhiteJavascript/aoe2-de-tools/pull/10 will be applied as well. 

From now on speed should be much better.

### CODE REVIEW

**Review by PeterWhiteJavascript — APPROVED** [review]

**Comment by PeterWhiteJavascript** [comment]
Everything should be working now. It's not letting me test locally in the same way as I was, but it seems to be working on the site.

**Comment by danielstaleiny** [comment]
how are you trying to run it ? what is not working ? do you use npm run start / build to run the code ?

npm run build takes care of generating the html from templates. 

Npm run start starts the express server while it triggers build before running it.

to dervrlep you can do 
npm run build -- --watch --serve 


I can help you out and document the sripts in README.md

**Comment by PeterWhiteJavascript** [comment]
Oh wait, I just restarted my IDE and it worked. Classic case of "Did you
turn it off and on again?".

Thanks :D

**Comment by danielstaleiny** [comment]
Happy that it works, let me know if you need help with the codebase.

**Pull request merged**
