### PR TITLE
Revert "Speed optimization of the villagers-required.html website"

### PR DESCRIPTION
**Pull request by PeterWhiteJavascript**
Reverts PeterWhiteJavascript/aoe2-de-tools#10

Gonna revert for now as it completely breaks the heroku link and I can't even seem to test locally.

### CODE REVIEW

**Comment by danielstaleiny** [comment]
Could you provide the error ? what is the build process ? 
Most likely you didn't install dependencies or tried to run it with different npm command.

Locally you need to do
```
npm install
```
and then run the express server with 
```
npm run start
```

**Comment by PeterWhiteJavascript** [comment]
Yeah, I just didn't put time into figuring it out. I'll do it tomorrow.

**Comment by danielstaleiny** [comment]
let me know the error when you have time, I can help you.

**Comment by PeterWhiteJavascript** [comment]
I've been super busy lately with streaming so I haven't done anything with
this yet. I'm just not sure exactly how I can get it to run with the heroku
host. Probably just takes a bit of digging as I can't even remember how it
works right now.

**Comment by danielstaleiny** [comment]
found the fix for the heroku app running issue, I pushed fix for it in here https://github.com/danielstaleiny/aoe2-de-tools/commit/1136bbf4d4c6f6235216eee68874a8878e427604 

you can validate that it is running on this page https://test-aoe2-build.herokuapp.com/.

Because you revert the pull-request, it is messing up the history, so the best way how to fix that is to force push and re-applied the turk gold patch which I am going to re-apply soon on top of the rest of the commits. 

I will make Pull request and you might have to force-push to be able to apply it.

**Comment by PeterWhiteJavascript** [comment]
For some reason it's still just giving me CANNOT GET '/' error when I try
to run the app locally. I'm just running the app and then navigating to
localhost:5000 which is how I had it set up before but it doesn't work now.

 I've done a few small changes to data files based on new balance. The one
thing I couldn't figure out how to fix was why monks with hussite reforms
don't show their new 100 food cost (the cost should go from 100 gold to 100
food)

**Comment by danielstaleiny** [comment]
should we hop into discord and you can share your setup and we can debug whatever the issue is.

**Pull request merged**
